# permissions for end users to view vvips.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vvip-viewer-role
rules:
- apiGroups:
  - vvip.vviphw.io
  resources:
  - vvips
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vvip.vviphw.io
  resources:
  - vvips/status
  verbs:
  - get
